services:
  postgres:
    image: postgres:15
    container_name: postgres15
    restart: unless-stopped
    environment:
      POSTGRES_USER: remembear
      POSTGRES_PASSWORD: remembear
      POSTGRES_DB: remembear
    ports:
      - "5432:5432"
    volumes:
      - postgres15_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - postgres-sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  postgres-sonar:
    image: postgres:15
    container_name: postgres-sonar
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_sonar_data:/var/lib/postgresql/data

volumes:
  postgres15_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_sonar_data: